<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class PersonSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('persons')->insert([
            [
                'identity_card' => '8064553',
                'identity_card_type' => 'CI',
                'identity_card_ext' => 'SC',
                'names' => 'JOSE CARLOS',
                'first_name' => 'HEREDIA',
                'last_name' => 'RODRIGUEZ',
                'birth_date' => date("Y-m-d H:i:s"),
                'gender' => 'M',
                'address' => '4to anillo radial ##',
                'telephone' => null,
                'email' => 'josecotoca@gmail.com',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s")
            ],
            [
                'identity_card' => '64684684',
                'identity_card_type' => 'CI',
                'identity_card_ext' => 'TR',
                'names' => 'MIGUEL',
                'first_name' => 'TERRAZAS',
                'last_name' => 'CASTRO',
                'birth_date' => date("Y-m-d H:i:s"),
                'gender' => 'M',
                'address' => '4to anillo radial ##',
                'telephone' => null,
                'email' => null,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s")
            ],
            [
                'identity_card' => '66574554',
                'identity_card_type' => 'CI',
                'identity_card_ext' => 'CB',
                'names' => 'MARIA LUISA',
                'first_name' => 'HERRERA',
                'last_name' => 'QUISPE',
                'birth_date' => date("Y-m-d H:i:s"),
                'gender' => 'F',
                'address' => '4to anillo radial ##',
                'telephone' => null,
                'email' => null,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s")
            ],
            [
                'identity_card' => '1114565',
                'identity_card_type' => 'CI',
                'identity_card_ext' => 'LP',
                'names' => 'JOSE MANUEL',
                'first_name' => 'LLANQUEE',
                'last_name' => 'SUAREZ',
                'birth_date' => date("Y-m-d H:i:s"),
                'gender' => 'F',
                'address' => null,
                'telephone' => null,
                'email' => null,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s")
            ],
            [
                'identity_card' => '669857',
                'identity_card_type' => 'CI',
                'identity_card_ext' => 'BN',
                'names' => 'MARIA JOSE',
                'first_name' => 'PEREIRA',
                'last_name' => 'LOSALES',
                'birth_date' => date("Y-m-d H:i:s"),
                'gender' => 'F',
                'address' => null,
                'telephone' => null,
                'email' => null,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s")
            ],
            [
                'identity_card' => '4596851',
                'identity_card_type' => 'CI',
                'identity_card_ext' => 'CB',
                'names' => 'RAUL',
                'first_name' => 'GONZALES',
                'last_name' => 'MORALES',
                'birth_date' => date("Y-m-d H:i:s"),
                'gender' => 'M',
                'address' => null,
                'telephone' => null,
                'email' => null,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s")
            ],
            [
                'identity_card' => '9999',
                'identity_card_type' => 'CI',
                'identity_card_ext' => 'CB',
                'names' => 'RAUL',
                'first_name' => 'XAVIER',
                'last_name' => 'NOGALES',
                'birth_date' => date("Y-m-d H:i:s"),
                'gender' => 'M',
                'address' => null,
                'telephone' => null,
                'email' => null,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s")
            ],
            [
                'identity_card' => '8888',
                'identity_card_type' => 'CI',
                'identity_card_ext' => 'CB',
                'names' => 'RAUL',
                'first_name' => 'PEDRO',
                'last_name' => 'CRUZ',
                'birth_date' => date("Y-m-d H:i:s"),
                'gender' => 'M',
                'address' => null,
                'telephone' => null,
                'email' => null,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s")
            ],
            [
                'identity_card' => '7777',
                'identity_card_type' => 'CI',
                'identity_card_ext' => 'CB',
                'names' => 'RAUL',
                'first_name' => 'AMANDA',
                'last_name' => 'CLAROS',
                'birth_date' => date("Y-m-d H:i:s"),
                'gender' => 'M',
                'address' => null,
                'telephone' => null,
                'email' => null,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s")
            ],
            [
                'identity_card' => '6666',
                'identity_card_type' => 'CI',
                'identity_card_ext' => 'CB',
                'names' => 'RAUL',
                'first_name' => 'ROBERTO',
                'last_name' => 'ESTEBAN',
                'birth_date' => date("Y-m-d H:i:s"),
                'gender' => 'M',
                'address' => null,
                'telephone' => null,
                'email' => null,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s")
            ],
            [
                'identity_card' => '5555',
                'identity_card_type' => 'CI',
                'identity_card_ext' => 'CB',
                'names' => 'RAUL',
                'first_name' => 'MARIA JOSE',
                'last_name' => 'SANABRIA',
                'birth_date' => date("Y-m-d H:i:s"),
                'gender' => 'M',
                'address' => null,
                'telephone' => null,
                'email' => null,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s")
            ],
            [
                'identity_card' => '4444',
                'identity_card_type' => 'CI',
                'identity_card_ext' => 'CB',
                'names' => 'RAUL',
                'first_name' => 'ESTEBAN',
                'last_name' => 'CALVO',
                'birth_date' => date("Y-m-d H:i:s"),
                'gender' => 'M',
                'address' => null,
                'telephone' => null,
                'email' => null,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s")
            ],
            [
                'identity_card' => '3333',
                'identity_card_type' => 'CI',
                'identity_card_ext' => 'CB',
                'names' => 'RAUL',
                'first_name' => 'CLEMENTELI',
                'last_name' => 'BORDA',
                'birth_date' => date("Y-m-d H:i:s"),
                'gender' => 'M',
                'address' => null,
                'telephone' => null,
                'email' => null,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s")
            ],
            [
                'identity_card' => '2222',
                'identity_card_type' => 'CI',
                'identity_card_ext' => 'CB',
                'names' => 'RAUL',
                'first_name' => 'ALVARADO',
                'last_name' => 'ROSALES',
                'birth_date' => date("Y-m-d H:i:s"),
                'gender' => 'M',
                'address' => null,
                'telephone' => null,
                'email' => null,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s")
            ],
            [
                'identity_card' => '1111',
                'identity_card_type' => 'CI',
                'identity_card_ext' => 'CB',
                'names' => 'RAUL',
                'first_name' => 'GUMUCIO',
                'last_name' => 'ESTEBAN',
                'birth_date' => date("Y-m-d H:i:s"),
                'gender' => 'M',
                'address' => null,
                'telephone' => null,
                'email' => null,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s")
            ]
        ]);


        $personsarray = array(
            array('identityCard'=>'100000001','names'=>'MARIA INES','firstName'=>'ORELLANO','lastName'=>'NICOLARI'),
            array('identityCard'=>'100000002','names'=>'RAQUEL ELIZABET','firstName'=>'CABRAL','lastName'=>'MARTINEZ'),
            array('identityCard'=>'100000003','names'=>'MARÍA ROSARIO','firstName'=>'GAMOU','lastName'=>'ROCHON'),
            array('identityCard'=>'100000004','names'=>'ALBERTO OSCAR','firstName'=>'PEREZ','lastName'=>'SILVA'),
            array('identityCard'=>'100000005','names'=>'ARIEL','firstName'=>'BALCARCEL','lastName'=>'BELOQUI'),
            array('identityCard'=>'100000006','names'=>'WINSTON FRANKLIN','firstName'=>'CARDANI','lastName'=>'SCHWARZ'),
            array('identityCard'=>'100000007','names'=>'PABLO DANIEL','firstName'=>'CECCONE','lastName'=>'SOSA'),
            array('identityCard'=>'100000008','names'=>'MERCEDES MARIA','firstName'=>'COELLO','lastName'=>'DE MARIA'),
            array('identityCard'=>'100000009','names'=>'JORGE MARIA','firstName'=>'CORREA','lastName'=>'BONILLA'),
            array('identityCard'=>'100000010','names'=>'ALCIDES','firstName'=>'COSTA','lastName'=>'HERNANDEZ'),
            array('identityCard'=>'100000011','names'=>'MIRTA GRACIELA','firstName'=>'DI GIOVANNI','lastName'=>'NUÑEZ'),
            array('identityCard'=>'100000012','names'=>'SERGIO','firstName'=>'EDELMAN','lastName'=>'SEADE'),
            array('identityCard'=>'100000013','names'=>'DORITA','firstName'=>'GARICOITS','lastName'=>'FERRARI'),
            array('identityCard'=>'100000014','names'=>'HUGO JOSE','firstName'=>'MARQUISIO','lastName'=>'MADERA'),
            array('identityCard'=>'100000015','names'=>'JOSE BARTOLOME','firstName'=>'RICCARDI','lastName'=>'MARTINEZ'),
            array('identityCard'=>'100000016','names'=>'NELSON EDUARDO','firstName'=>'RODRIGUEZ','lastName'=>'PEREIRA'),
            array('identityCard'=>'100000017','names'=>'JUAN CARLOS','firstName'=>'RODRIGUEZ','lastName'=>'PEREZ'),
            array('identityCard'=>'100000018','names'=>'MARTHA VANDA','firstName'=>'TOSCANO','lastName'=>'SOSA'),
            array('identityCard'=>'100000019','names'=>'MABEL','firstName'=>'UMPIERREZ','lastName'=>'CABRERA'),
            array('identityCard'=>'100000020','names'=>'EFRAIN ANDRES','firstName'=>'GRAZIUSO','lastName'=>'GUTIERREZ'),
            array('identityCard'=>'100000021','names'=>'VICTOR ESTEBAN','firstName'=>'ROCHA','lastName'=>'PROSPERO'),
            array('identityCard'=>'100000022','names'=>'GERARDO','firstName'=>'ARTURO','lastName'=>'SARASOLA'),
            array('identityCard'=>'100000023','names'=>'ERNESTO','firstName'=>'ODAZZIO','lastName'=>'LOMBARDO'),
            array('identityCard'=>'100000024','names'=>'STELLA SERRANA','firstName'=>'CITTADINO','lastName'=>'PEREIRO'),
            array('identityCard'=>'100000025','names'=>'TABARE','firstName'=>'GONZALEZ','lastName'=>'AGUILAR'),
            array('identityCard'=>'100000026','names'=>'SILVIA','firstName'=>'BOZZOLASCO','lastName'=>'PAIS'),
            array('identityCard'=>'100000027','names'=>'CLAUDIO MARTIN','firstName'=>'ECHEVARRIA','lastName'=>'CORBO'),
            array('identityCard'=>'100000028','names'=>'VICTOR HUGO','firstName'=>'DE AZIZ','lastName'=>'DANIELE'),
            array('identityCard'=>'100000029','names'=>'JOSE EDUARDO','firstName'=>'BRESCIA','lastName'=>'SEPILOV'),
            array('identityCard'=>'100000030','names'=>'JOSE MARIA','firstName'=>'ARENAS','lastName'=>'RIJO'),
            array('identityCard'=>'100000031','names'=>'MARÍA ROSA','firstName'=>'DELEO','lastName'=>'GOMEZ'),
            array('identityCard'=>'100000032','names'=>'CARLOS WALDEMAR','firstName'=>'CARRIQUIRY','lastName'=>'BARCIA'),
            array('identityCard'=>'100000033','names'=>'ESTEBAN RAUL','firstName'=>'CHAVES','lastName'=>'BERHQUET'),
            array('identityCard'=>'100000034','names'=>'ROBERTO','firstName'=>'GONZALEZ','lastName'=>'ECHEVERRY'),
            array('identityCard'=>'100000035','names'=>'EDGARDO RAMON','firstName'=>'VERA','lastName'=>'BRITOS'),
            array('identityCard'=>'100000036','names'=>'DENISE HAIFA','firstName'=>'ECCHER','lastName'=>'DE MELLO'),
            array('identityCard'=>'100000037','names'=>'MIGUEL ANGEL','firstName'=>'SANCHEZ','lastName'=>'SANCHEZ'),
            array('identityCard'=>'100000038','names'=>'CARLOS','firstName'=>'CENTURION','lastName'=>'BARRIO'),
            array('identityCard'=>'100000039','names'=>'MANUEL NARCISO','firstName'=>'BONINO','lastName'=>'PEÑA'),
            array('identityCard'=>'100000040','names'=>'RUBEN DARIO','firstName'=>'ECHEVERRY','lastName'=>'DINI'),
            array('identityCard'=>'100000041','names'=>'MARIO BERNABE','firstName'=>'BETOLAZA','lastName'=>'DINI'),
            array('identityCard'=>'100000042','names'=>'YAMANDU','firstName'=>'CORRAL','lastName'=>'PEDROZZA'),
            array('identityCard'=>'100000043','names'=>'NILSON ANGEL','firstName'=>'BALOSTRO','lastName'=>'CAMMARANO'),
            array('identityCard'=>'100000044','names'=>'ASUCENA','firstName'=>'BRAUSE','lastName'=>'DEACES'),
            array('identityCard'=>'100000045','names'=>'LUIS','firstName'=>'CASTELAR','lastName'=>'CHIAPPA'),
            array('identityCard'=>'100000046','names'=>'RICARDO','firstName'=>'COURIEL','lastName'=>'MENDOZA'),
            array('identityCard'=>'100000047','names'=>'DANIEL','firstName'=>'DIAZ','lastName'=>'BRIT'),
            array('identityCard'=>'100000048','names'=>'MIGUEL','firstName'=>'DIAZ','lastName'=>'RUSIÑOL'),
            array('identityCard'=>'100000049','names'=>'JOSE ANTONIO','firstName'=>'ZUNINO','lastName'=>'VEDAIN'),
            array('identityCard'=>'100000050','names'=>'HUMBERTO RAMÀN','firstName'=>'GARCIA','lastName'=>'BLENGIO'),
            array('identityCard'=>'100000051','names'=>'JUAN CARLOS','firstName'=>'DE LA IGLESIA','lastName'=>'MONTANS'),
            array('identityCard'=>'100000052','names'=>'MARIA GABRIELA','firstName'=>'REYES','lastName'=>'LEMES'),
            array('identityCard'=>'100000053','names'=>'FELIPE JOSE','firstName'=>'CASAS','lastName'=>'DE LOS SANTOS'),
            array('identityCard'=>'100000054','names'=>'VERONICA','firstName'=>'ANDRADE','lastName'=>'MOREIRA'),
            array('identityCard'=>'100000055','names'=>'MARÍA LUISA','firstName'=>'GONZALEZ','lastName'=>'BERDIÑAS'),
            array('identityCard'=>'100000056','names'=>'NESTOR DANIEL','firstName'=>'QUEIJO','lastName'=>'SAIBENE'),
            array('identityCard'=>'100000057','names'=>'LUIS LEONARDO','firstName'=>'BOIX','lastName'=>'BELEN'),
            array('identityCard'=>'100000058','names'=>'MARIA GRACIELA','firstName'=>'BRUSA','lastName'=>'FREDES'),
            array('identityCard'=>'100000059','names'=>'SILVANA JACQULINE','firstName'=>'PERDOMO','lastName'=>'CHIAPPARA'),
            array('identityCard'=>'100000060','names'=>'GERARDO','firstName'=>'GIAMBRUNO','lastName'=>'FIRPI'),
            array('identityCard'=>'100000061','names'=>'GABRIELA','firstName'=>'CARAMES','lastName'=>'FLUMINI'),
            array('identityCard'=>'100000062','names'=>'ALEJANDRO ANDRES','firstName'=>'CONTI','lastName'=>'HAUW'),
            array('identityCard'=>'100000063','names'=>'JOSE LUIS','firstName'=>'CAMACHO','lastName'=>'MAY'),
            array('identityCard'=>'100000064','names'=>'LEONARDO GUSTAVO','firstName'=>'IGLESIAS','lastName'=>'MONTAÑO'),
            array('identityCard'=>'100000065','names'=>'VERONICA MARIA','firstName'=>'ABALOS','lastName'=>'RODRIGUEZ'),
            array('identityCard'=>'100000066','names'=>'GONZALO','firstName'=>'GRAÑA','lastName'=>'CASAS'),
            array('identityCard'=>'100000067','names'=>'NOEMI LYDIA','firstName'=>'BRECCIA','lastName'=>'ALONZO'),
            array('identityCard'=>'100000068','names'=>'MARIA DEL CARMEN','firstName'=>'CONDE','lastName'=>'BOGLIOLO'),
            array('identityCard'=>'100000069','names'=>'MARIA JIMENA','firstName'=>'RIVERO','lastName'=>'CORRAL'),
            array('identityCard'=>'100000070','names'=>'MARY CRISTINA','firstName'=>'O BRIEN','lastName'=>'DE LA FUENTE'),
            array('identityCard'=>'100000071','names'=>'ROSA M','firstName'=>'ABREU','lastName'=>'ESCURSELL'),
            array('identityCard'=>'100000072','names'=>'RAMIRO','firstName'=>'CABALLERO','lastName'=>'FERNANDEZ'),
            array('identityCard'=>'100000073','names'=>'LUIS','firstName'=>'LARROSA','lastName'=>'FERNANDEZ'),
            array('identityCard'=>'100000074','names'=>'JORGE ANTONIO','firstName'=>'MONTERO','lastName'=>'IZETTA'),
            array('identityCard'=>'100000075','names'=>'PABLO EMILIANO','firstName'=>'FERRARI','lastName'=>'LOPEZ'),
            array('identityCard'=>'100000076','names'=>'JUAN MARTIN','firstName'=>'SILVERA','lastName'=>'MARTINEZ'),
            array('identityCard'=>'100000077','names'=>'ANALIA','firstName'=>'DE BELLIS','lastName'=>'MAUVEZIN'),
            array('identityCard'=>'100000078','names'=>'ALVARO BOLIVAR','firstName'=>'MENDEZ','lastName'=>'RODRIGUEZ'),
            array('identityCard'=>'100000079','names'=>'ALFREDO','firstName'=>'PEDULLA','lastName'=>'SALDIAS'),
            array('identityCard'=>'100000080','names'=>'ALEJANDRO','firstName'=>'VARELA','lastName'=>'SAMUDIO'),
            array('identityCard'=>'100000081','names'=>'FERNANDO TOMAS','firstName'=>'PEREIRA','lastName'=>'ORTIZ'),
            array('identityCard'=>'100000082','names'=>'HUGO','firstName'=>'ALVAREZ','lastName'=>'GRIMON'),
            array('identityCard'=>'100000083','names'=>'ALICIA TERESITA','firstName'=>'ANTONELLI','lastName'=>'HOURCADE'),
            array('identityCard'=>'100000084','names'=>'GERARDO JAVIER','firstName'=>'BIDEGAIN','lastName'=>'IZQUIERDO'),
            array('identityCard'=>'100000085','names'=>'HUBERTO NILSON','firstName'=>'CASTROMAN','lastName'=>'VIERA'),
            array('identityCard'=>'100000086','names'=>'ANTONIO','firstName'=>'CORREA LUNA','lastName'=>'VIERA'),
            array('identityCard'=>'100000087','names'=>'MIGUEL ANGEL','firstName'=>'DRAPER','lastName'=>'VILA'),
            array('identityCard'=>'100000088','names'=>'MARTHA ELIZABETH','firstName'=>'FERNADEZ','lastName'=>'FIORELLI'),
            array('identityCard'=>'100000089','names'=>'VICTOR RICARDO','firstName'=>'GIORELLO','lastName'=>'SASTRE'),
            array('identityCard'=>'100000090','names'=>'RUBEN ARI','firstName'=>'HENRY','lastName'=>'SARALEGUI'),
            array('identityCard'=>'100000091','names'=>'ROQUE GASTON','firstName'=>'HERNANDEZ','lastName'=>'APARICIO'),
            array('identityCard'=>'100000092','names'=>'AMERICO','firstName'=>'NOBOA','lastName'=>'CHALELA'),
            array('identityCard'=>'100000093','names'=>'ANA CAROLINA','firstName'=>'RECAREY','lastName'=>'FERNANDEZ'),
            array('identityCard'=>'100000094','names'=>'EVA MYRIAN','firstName'=>'SANTOS','lastName'=>'ROCCA'),
            array('identityCard'=>'100000095','names'=>'ALVARO MARTIN','firstName'=>'VILA','lastName'=>'DE NICOLA'),
            array('identityCard'=>'100000096','names'=>'MARISA DANIELA','firstName'=>'ALMIRON','lastName'=>'CEDRES'),
            array('identityCard'=>'100000097','names'=>'JUAN PABLO','firstName'=>'LUSSICH','lastName'=>'MACHADO'),
            array('identityCard'=>'100000098','names'=>'FERNANDO','firstName'=>'REPETTO','lastName'=>'LUSARARIAN'),
            array('identityCard'=>'100000099','names'=>'SYLVIA','firstName'=>'GUIDO','lastName'=>'MAZZULA'),
            array('identityCard'=>'100000100','names'=>'MARCELO','firstName'=>'GIL','lastName'=>'ROSSO'),
            array('identityCard'=>'100000101','names'=>'HUGO ARIEL','firstName'=>'LEOPOLD','lastName'=>'LOPEZ'),
            array('identityCard'=>'100000102','names'=>'GERARDO ANDRES','firstName'=>'SALSAMENDI','lastName'=>'AMY'),
            array('identityCard'=>'100000103','names'=>'JUAN JUSTO','firstName'=>'ORELLANO','lastName'=>'FERNANDEZ'),
            array('identityCard'=>'100000104','names'=>'RUBEN JOSE','firstName'=>'BERTON','lastName'=>'BATLLE'),
            array('identityCard'=>'100000105','names'=>'RUBEN WILLIAMS','firstName'=>'SILVERA','lastName'=>'TEJERA'),
            array('identityCard'=>'100000106','names'=>'ELDER DIEGO','firstName'=>'PERRONI','lastName'=>'CORREA'),
            array('identityCard'=>'100000107','names'=>'FERNANDO','firstName'=>'STIPANICIC','lastName'=>'SUAREZ'),
            array('identityCard'=>'100000108','names'=>'LUIS','firstName'=>'UMPIERREZ','lastName'=>'FRANCA'),
            array('identityCard'=>'100000109','names'=>'IRLE MAIDER','firstName'=>'LISSIO','lastName'=>'BENOIT'),
            array('identityCard'=>'100000110','names'=>'FRANCISCO JAVIER','firstName'=>'BONNAHON','lastName'=>'DEFELIPO'),
            array('identityCard'=>'100000111','names'=>'JOSE GERARDO','firstName'=>'LODEIRO','lastName'=>'DUHALDE'),
            array('identityCard'=>'100000112','names'=>'JOSE ANTONIO','firstName'=>'ALVAREZ','lastName'=>'VALDEZ'),
            array('identityCard'=>'100000113','names'=>'LUIS HECTOR','firstName'=>'ESTEVEZ','lastName'=>'DA MARIA'),
            array('identityCard'=>'100000114','names'=>'NIRIA','firstName'=>'PICERNO','lastName'=>'ALVAREZ DE RON'),
            array('identityCard'=>'100000115','names'=>'HECTOR DANIEL','firstName'=>'REYES','lastName'=>'IGUINI'),
            array('identityCard'=>'100000116','names'=>'JAVIER ZENON','firstName'=>'SALARI','lastName'=>'MARTINO'),
            array('identityCard'=>'100000117','names'=>'LUIS ALBERTO','firstName'=>'RUIZ','lastName'=>'MARTINO'),
            array('identityCard'=>'100000118','names'=>'RAFAEL','firstName'=>'ASTI','lastName'=>'BEHERENS'),
            array('identityCard'=>'100000119','names'=>'ALBERTO FABIAN','firstName'=>'GOMEZ','lastName'=>'BEHRENS'),
            array('identityCard'=>'100000120','names'=>'MARIA ISABEL','firstName'=>'GERICKE','lastName'=>'BEHRENS'),
            array('identityCard'=>'100000121','names'=>'SEBASTIAN','firstName'=>'PIRIA','lastName'=>'CORBI'),
            array('identityCard'=>'100000122','names'=>'ANA MONICA','firstName'=>'PALMA','lastName'=>'ALBINO'),
            array('identityCard'=>'100000123','names'=>'NORA ALICIA','firstName'=>'ORELLANO','lastName'=>'MARTINEZ'),
            array('identityCard'=>'100000124','names'=>'WALDEMAR HEBERT','firstName'=>'ARAUJO','lastName'=>'LEON'),
            array('identityCard'=>'100000125','names'=>'MARIA MERCEDES','firstName'=>'CABRERA','lastName'=>'CANTONI'),
            array('identityCard'=>'100000126','names'=>'ENRIQUE ANDRES','firstName'=>'CABRERA','lastName'=>'SANTINI'),
            array('identityCard'=>'100000127','names'=>'FERNANDO','firstName'=>'CASAS','lastName'=>'SETELICH'),
            array('identityCard'=>'100000128','names'=>'ALEJANDRO','firstName'=>'CASTRO','lastName'=>'GOYOAGA'),
            array('identityCard'=>'100000129','names'=>'OLIVERA','firstName'=>'DIAZ','lastName'=>'LORENZO'),
            array('identityCard'=>'100000130','names'=>'FREDIS','firstName'=>'ROSSI','lastName'=>'DOMINGUEZ'),
            array('identityCard'=>'100000131','names'=>'MARIO','firstName'=>'SCHIAPPACASSE','lastName'=>'MIER'),
            array('identityCard'=>'100000132','names'=>'PABLO','firstName'=>'GHIONE','lastName'=>'LEAL'),
            array('identityCard'=>'100000133','names'=>'DANIEL','firstName'=>'MONTANO','lastName'=>'DE LA ROSA'),
            array('identityCard'=>'100000134','names'=>'PEDRO ROQUE','firstName'=>'MORE','lastName'=>'ROMANO'),
            array('identityCard'=>'100000135','names'=>'GABRIEL','firstName'=>'VEGA','lastName'=>'DUARTE'),
            array('identityCard'=>'100000136','names'=>'RAMON FRANCISCO','firstName'=>'PETROCELLI','lastName'=>'MENA'),
            array('identityCard'=>'100000137','names'=>'LAURA','firstName'=>'ALVAREZ','lastName'=>'NICOLINI'),
            array('identityCard'=>'100000138','names'=>'MIRIAM AMELIA','firstName'=>'MURIA','lastName'=>'REFRESQUINI'),
            array('identityCard'=>'100000139','names'=>'ROQUE DANIEL','firstName'=>'DENBY','lastName'=>'SERRON'),
            array('identityCard'=>'100000140','names'=>'IGNACIO','firstName'=>'MALLO','lastName'=>'LOPEZ'),
            array('identityCard'=>'100000141','names'=>'JOSE LUIS','firstName'=>'BENTANCUR','lastName'=>'FERREIRA'),
            array('identityCard'=>'100000142','names'=>'DANIEL HUGO','firstName'=>'BERTONI','lastName'=>'RODRIGUEZ'),
            array('identityCard'=>'100000143','names'=>'MARY BEATRIZ','firstName'=>'DIZ','lastName'=>'AYALA'),
            array('identityCard'=>'100000144','names'=>'LIDIA','firstName'=>'EZCURRA','lastName'=>'BARREIRO'),
            array('identityCard'=>'100000145','names'=>'HUGO ROMAN','firstName'=>'GANDOLFO','lastName'=>'CAZAJOUS'),
            array('identityCard'=>'100000146','names'=>'GABRIELA ---','firstName'=>'LUZARDO','lastName'=>'NANDE'),
            array('identityCard'=>'100000147','names'=>'ALICIA','firstName'=>'PUERTO','lastName'=>'POSADA'),
            array('identityCard'=>'100000148','names'=>'HUBERT','firstName'=>'RIVA','lastName'=>'RODRIGUEZ'),
            array('identityCard'=>'100000149','names'=>'GUALBERTO','firstName'=>'ROLAND','lastName'=>'WETHERALL'),
            array('identityCard'=>'100000150','names'=>'EDUARDO','firstName'=>'VEGA','lastName'=>'MORALES'),
            array('identityCard'=>'100000151','names'=>'MATEO DANIEL','firstName'=>'VERGARA','lastName'=>'PICHON'),
            array('identityCard'=>'100000152','names'=>'DIVAR DANIEL','firstName'=>'MAGLIA','lastName'=>'BACHINI'),
            array('identityCard'=>'100000153','names'=>'JOSE SEBASTIAN','firstName'=>'SEGREDO','lastName'=>'IHLENFELD'),
            array('identityCard'=>'100000154','names'=>'ADRIANA RAQUEL','firstName'=>'ALVAREZ','lastName'=>'MARTINEZ'),
            array('identityCard'=>'100000155','names'=>'MIRIAM GUIOMAR','firstName'=>'ROMANO','lastName'=>'CESAR'),
            array('identityCard'=>'100000156','names'=>'CARLOS VALERIO','firstName'=>'FERREIRA','lastName'=>'ARGUL'),
            array('identityCard'=>'100000157','names'=>'ENRIQUE','firstName'=>'GONZALEZ','lastName'=>'LINN'),
            array('identityCard'=>'100000158','names'=>'ISMAEL','firstName'=>'RAMAGLI','lastName'=>'MONCE'),
            array('identityCard'=>'100000159','names'=>'MARIA ELIDA','firstName'=>'FRANCA','lastName'=>'MARSANO'),
            array('identityCard'=>'100000160','names'=>'MANUEL ERNESTO','firstName'=>'SUAREZ','lastName'=>'VILLAMIL'),
            array('identityCard'=>'100000161','names'=>'RIVERA','firstName'=>'BEYHAUT','lastName'=>'LUCCHETTI'),
            array('identityCard'=>'100000162','names'=>'RICARDO','firstName'=>'DELGADO','lastName'=>'BERAZA'),
            array('identityCard'=>'100000163','names'=>'RODRIGO MIGUEL','firstName'=>'GUINEA','lastName'=>'RODRIGUEZ'),
            array('identityCard'=>'100000164','names'=>'JUAN CARLOS','firstName'=>'LLANES','lastName'=>'FERREIRO'),
            array('identityCard'=>'100000165','names'=>'CARLOS DOMINGO','firstName'=>'RICHINO','lastName'=>'D`APOLITO'),
            array('identityCard'=>'100000166','names'=>'JOSE ANDRES','firstName'=>'ALZA','lastName'=>'GULLA'),
            array('identityCard'=>'100000167','names'=>'RODRIGO','firstName'=>'DUARTE','lastName'=>'LEMA'),
            array('identityCard'=>'100000168','names'=>'OSCAR','firstName'=>'MESSERE','lastName'=>'NARANJA'),
            array('identityCard'=>'100000169','names'=>'ROQUE EDISON','firstName'=>'DELLA VENTURA','lastName'=>'LOUREIRO'),
            array('identityCard'=>'100000170','names'=>'CLAUDIA','firstName'=>'CASTGLIONI','lastName'=>'PRATS'),
            array('identityCard'=>'100000171','names'=>'ELIZABETH','firstName'=>'YACKS','lastName'=>'SOÑORA'),
            array('identityCard'=>'100000172','names'=>'SERGIO RAUL','firstName'=>'ALVEZ','lastName'=>'CARLI'),
            array('identityCard'=>'100000173','names'=>'JOSE PABLO','firstName'=>'ROCCO','lastName'=>'PEREZ'),
            array('identityCard'=>'100000174','names'=>'SILVIA','firstName'=>'PEREIRA CASTRO','lastName'=>'PORRINI'),
            array('identityCard'=>'100000175','names'=>'SERGIO','firstName'=>'NIFFOURI','lastName'=>'TAPIA'),
            array('identityCard'=>'100000176','names'=>'MARIA TERESA','firstName'=>'PENA','lastName'=>'ESPONDA'),
            array('identityCard'=>'100000177','names'=>'JULIO CESAR','firstName'=>'SAPRIZA','lastName'=>'POLLA'),
            array('identityCard'=>'100000178','names'=>'ENRIQUE','firstName'=>'SARMIENTO','lastName'=>'SUAREZ'),
            array('identityCard'=>'100000179','names'=>'ADRIANA LAURA','firstName'=>'CABRERA','lastName'=>'DIVERIO'),
            array('identityCard'=>'100000180','names'=>'SERGIO MARIO','firstName'=>'GILGORRI','lastName'=>'RECUERO'),
            array('identityCard'=>'100000181','names'=>'MIGUEL MEDARDO','firstName'=>'PASARELLO','lastName'=>'SANCHIS'),
            array('identityCard'=>'100000182','names'=>'ALFREDO ANGEL','firstName'=>'ALVEZ','lastName'=>'PATRONE'),
            array('identityCard'=>'100000183','names'=>'DIEGO','firstName'=>'COSSE','lastName'=>'AGUERRE'),
            array('identityCard'=>'100000184','names'=>'DARIO','firstName'=>'RUIBAL','lastName'=>'MAÑANA'),
            array('identityCard'=>'100000185','names'=>'DANILO','firstName'=>'VALLVERDU','lastName'=>'AIZPUN'),
            array('identityCard'=>'100000186','names'=>'JUAN','firstName'=>'RELOBA','lastName'=>'CANNELLA'),
            array('identityCard'=>'100000187','names'=>'JOSE MARIA','firstName'=>'GONZALEZ','lastName'=>'BLANC'),
            array('identityCard'=>'100000188','names'=>'CARLOS FRANCISCO','firstName'=>'MONTEIRO','lastName'=>'ROSSARI'),
            array('identityCard'=>'100000189','names'=>'LUIS ALBERTO','firstName'=>'RIVAS','lastName'=>'AUNES'),
            array('identityCard'=>'100000190','names'=>'OLDEMAR JACINTO','firstName'=>'GONZALEZ','lastName'=>'BURONI'),
            array('identityCard'=>'100000191','names'=>'ANDREA','firstName'=>'MORATO','lastName'=>'FERRARO'),
            array('identityCard'=>'100000192','names'=>'DARDO','firstName'=>'MUÑECAS','lastName'=>'KETENYIAN'),
            array('identityCard'=>'100000193','names'=>'ANA PATRICIA','firstName'=>'MARTINEZ','lastName'=>'DIMPERIO'),
            array('identityCard'=>'100000194','names'=>'BEATRIZ MARIA','firstName'=>'MARTINEZ','lastName'=>'MASSONE'),
            array('identityCard'=>'100000195','names'=>'TERESITA','firstName'=>'PIÑEYRUA','lastName'=>'TEJERA'),
            array('identityCard'=>'100000196','names'=>'HERNANN ERIC','firstName'=>'REY','lastName'=>'GALLO'),
            array('identityCard'=>'100000197','names'=>'PABLO EDUARDO','firstName'=>'DE SALTERAIN','lastName'=>'TESAURO'),
            array('identityCard'=>'100000198','names'=>'KARINA','firstName'=>'BARRIOLA','lastName'=>'NICOLETTI'),
            array('identityCard'=>'100000199','names'=>'JOSÉ ALBERTO','firstName'=>'BAZ','lastName'=>'ARISMENDI'),
            array('identityCard'=>'100000200','names'=>'CARLOS RENZO','firstName'=>'BELLO','lastName'=>'BARBOZA'),
            array('identityCard'=>'100000201','names'=>'VICTOR','firstName'=>'BENTABERRI','lastName'=>'BALATTI'),
            array('identityCard'=>'100000202','names'=>'RUBEN ANIBAL','firstName'=>'BERTA','lastName'=>'FELIPEZ'),
            array('identityCard'=>'100000203','names'=>'GABRIEL ALEJANDRO','firstName'=>'BLANCO','lastName'=>'SEVERO'),
            array('identityCard'=>'100000204','names'=>'NINO','firstName'=>'CALZADA','lastName'=>'GIMENEZ'),
            array('identityCard'=>'100000205','names'=>'DORA','firstName'=>'CERUTTI','lastName'=>'CAMPOS'),
            array('identityCard'=>'100000206','names'=>'HEBERT','firstName'=>'BATOVSKY','lastName'=>'GIGLIO'),
            array('identityCard'=>'100000207','names'=>'LUIS MARIA','firstName'=>'FERRARIS','lastName'=>'CASTELLS'),
            array('identityCard'=>'100000208','names'=>'GONZALO','firstName'=>'GARCIA','lastName'=>'PERG'),
            array('identityCard'=>'100000209','names'=>'JUAN DANIEL','firstName'=>'MARTINEZ','lastName'=>'ALVAREZ'),
            array('identityCard'=>'100000210','names'=>'JOSE ALBERTO','firstName'=>'MARTIRENA','lastName'=>'DOMATO'),
            array('identityCard'=>'100000211','names'=>'ADRIANA','firstName'=>'OLIVERA','lastName'=>'ETCHATZ'),
            array('identityCard'=>'100000212','names'=>'DANIEL BERNABE','firstName'=>'PAVON','lastName'=>'PONCE DE LEON'),
            array('identityCard'=>'100000213','names'=>'CARLOS','firstName'=>'QUEVEDO','lastName'=>'CIBILS'),
            array('identityCard'=>'100000214','names'=>'CARLOS HUMBERTO','firstName'=>'SALVERAGLIO','lastName'=>'SUAREZ'),
            array('identityCard'=>'100000215','names'=>'IVONNE','firstName'=>'SANTESTEVAN','lastName'=>'ALMANDOS'),
            array('identityCard'=>'100000216','names'=>'GONZALO RAMON','firstName'=>'SILVEIRA','lastName'=>'SILVA'),
            array('identityCard'=>'100000217','names'=>'WASHINGTON ULISES','firstName'=>'TEJERA','lastName'=>'CAMPELO'),
            array('identityCard'=>'100000218','names'=>'ALBERTO','firstName'=>'TELLECHEA','lastName'=>'SILVA'),
            array('identityCard'=>'100000219','names'=>'GONZALO','firstName'=>'VIGNOLI','lastName'=>'PEREZ'),
            array('identityCard'=>'100000220','names'=>'EDUARDO IGNACIO','firstName'=>'MAGGI','lastName'=>'ROQUETA'),
            array('identityCard'=>'100000221','names'=>'MARIO ISIDRO','firstName'=>'PORTAS','lastName'=>'AILLAUME'),
            array('identityCard'=>'100000222','names'=>'JULIO CESAR','firstName'=>'ANGELINI','lastName'=>'ZABALLA'),
            array('identityCard'=>'100000223','names'=>'HECTOR CARLOS','firstName'=>'AYALA','lastName'=>'FASSIO'),
            array('identityCard'=>'100000224','names'=>'GUSTAVO ADOLFO','firstName'=>'KNOBEL','lastName'=>'CARABALLO'),
            array('identityCard'=>'100000225','names'=>'CARLOS','firstName'=>'DURAÑONA','lastName'=>'RIVERO'),
            array('identityCard'=>'100000226','names'=>'VERONICA','firstName'=>'DAMASCO','lastName'=>'CARSOGLIO'),
            array('identityCard'=>'100000227','names'=>'EDUARDO ALBERTO','firstName'=>'PEREZ','lastName'=>'CARSOGLIO'),
            array('identityCard'=>'100000228','names'=>'MARIO NELSON','firstName'=>'HERMIDA','lastName'=>'MACCIO'),
            array('identityCard'=>'100000229','names'=>'GONZALO MAURICIO','firstName'=>'SOSA','lastName'=>'ROSA'),
            array('identityCard'=>'100000230','names'=>'GRACIELA TERESA','firstName'=>'HERRERA','lastName'=>'DE LA FUENTE'),
            array('identityCard'=>'100000231','names'=>'GUSTAVO ADRIAN','firstName'=>'RIERA','lastName'=>'PEREYRA'),
            array('identityCard'=>'100000232','names'=>'MARIO  GUIDO','firstName'=>'ALVAREZ','lastName'=>'BENTANCOR'),
            array('identityCard'=>'100000233','names'=>'WILSON RAMON','firstName'=>'GARCIA','lastName'=>'DE LEON'),
            array('identityCard'=>'100000234','names'=>'PABLO HUGO','firstName'=>'AVIAGA','lastName'=>'DANREE'),
            array('identityCard'=>'100000235','names'=>'CARLOS','firstName'=>'BRUGMAN','lastName'=>'ELDUAYEN'),
            array('identityCard'=>'100000236','names'=>'WLADIMIR','firstName'=>'CABRERA','lastName'=>'FERNANDEZ'),
            array('identityCard'=>'100000237','names'=>'VICTOR','firstName'=>'ROSSI','lastName'=>'LASSO'),
            array('identityCard'=>'100000238','names'=>'SILVESTRE ---','firstName'=>'ROSSI','lastName'=>'RECUERO'),
            array('identityCard'=>'100000239','names'=>'FABRIELA','firstName'=>'BERTERRECHE','lastName'=>'SANCHEZ'),
            array('identityCard'=>'100000240','names'=>'GERMAN','firstName'=>'CARRIQUIRY','lastName'=>'VIANA'),
            array('identityCard'=>'100000241','names'=>'ISMAEL RAUL','firstName'=>'HERMIDA','lastName'=>'GENERALLI'),
            array('identityCard'=>'100000242','names'=>'RAQUEL AMALIA','firstName'=>'MARTIRENA','lastName'=>'GOYTIÑO'),
            array('identityCard'=>'100000243','names'=>'HUMBERTO','firstName'=>'MASOLLER','lastName'=>'GARRIDO'),
            array('identityCard'=>'100000244','names'=>'VICTOR MARIA','firstName'=>'RAPETTI','lastName'=>'RIOS'),
            array('identityCard'=>'100000245','names'=>'OSCAR GUSTAVO','firstName'=>'RIDAO','lastName'=>'MAIO'),
            array('identityCard'=>'100000246','names'=>'JUAN CARLOS','firstName'=>'TOZZO','lastName'=>'PEREGALLI'),
            array('identityCard'=>'100000247','names'=>'SIOMARA','firstName'=>'SCAGLIOLA','lastName'=>'SALIWONCHIK'),
            array('identityCard'=>'100000248','names'=>'MARIA SOLEDAD','firstName'=>'MARTINEZ','lastName'=>'SPINELLI'),
            array('identityCard'=>'100000249','names'=>'ANA MARIA','firstName'=>'IGLESIAS','lastName'=>'SILVERA'),
            array('identityCard'=>'100000250','names'=>'PABLO','firstName'=>'RAMIREZ','lastName'=>'DE SOUZA'),
            array('identityCard'=>'100000251','names'=>'HECTOR CICERON','firstName'=>'SANGENIS','lastName'=>'LUCHINI'),
            array('identityCard'=>'100000252','names'=>'JULIANA','firstName'=>'LESA','lastName'=>'LOZANO'),
            array('identityCard'=>'100000253','names'=>'ARTIGAS ALEXIS','firstName'=>'NIETO','lastName'=>'MOURIN'),
            array('identityCard'=>'100000254','names'=>'DANIEL HONORIO','firstName'=>'MAGNONE','lastName'=>'COGO'),
            array('identityCard'=>'100000255','names'=>'OSCAR DIEGO','firstName'=>'LIMA','lastName'=>'DIAZ'),
            array('identityCard'=>'100000256','names'=>'RAFAEL ARTURO','firstName'=>'DE GROSSI','lastName'=>'MENDARO'),
            array('identityCard'=>'100000257','names'=>'JORGE OTTO','firstName'=>'CEDRES','lastName'=>'BONILLA'),
            array('identityCard'=>'100000258','names'=>'HAYDEE EMILIA','firstName'=>'GARCIA','lastName'=>'PEREIRA DAS NEVES'),
            array('identityCard'=>'100000259','names'=>'HECTOR','firstName'=>'FIORELLI','lastName'=>'MUNIZ'),
            array('identityCard'=>'100000260','names'=>'FAVIO DANIEL','firstName'=>'CAL','lastName'=>'GRASSI'),
            array('identityCard'=>'100000261','names'=>'JULIO JOSE','firstName'=>'MORALES','lastName'=>'ANDRIOLO'),
            array('identityCard'=>'100000262','names'=>'EDUARDO','firstName'=>'PEÑALOZA','lastName'=>'ASTRALDI'),
            array('identityCard'=>'100000263','names'=>'ISABELINO WILSON','firstName'=>'PEDREIRA','lastName'=>'BELEA'),
            array('identityCard'=>'100000264','names'=>'ROBERTO BENJAMIN','firstName'=>'RAMOS','lastName'=>'CANZANI'),
            array('identityCard'=>'100000265','names'=>'JOSE ARTURO','firstName'=>'PARDIÑAS','lastName'=>'SUAREZ'),
            array('identityCard'=>'100000266','names'=>'EDITH ELENA','firstName'=>'RAMIREZ','lastName'=>'ECHEVERRIA'),
            array('identityCard'=>'100000267','names'=>'ROBERTO','firstName'=>'ROMANO','lastName'=>'LEMOLE'),
            array('identityCard'=>'100000268','names'=>'ANA MARIA','firstName'=>'CATALDO','lastName'=>'CAULA'),
            array('identityCard'=>'100000269','names'=>'MARIA CRISTINA','firstName'=>'GLOODTDOFSKY','lastName'=>'NOBRE'),
            array('identityCard'=>'100000270','names'=>'VICTORIA','firstName'=>'RODRIGUEZ','lastName'=>'SILVERA'),
            array('identityCard'=>'100000271','names'=>'RONI LUCAS','firstName'=>'MENDEZ','lastName'=>'BOUNOUS'),
            array('identityCard'=>'100000272','names'=>'GUSTAVO ROBERTO','firstName'=>'BENTOS','lastName'=>'CAMPARI'),
            array('identityCard'=>'100000273','names'=>'JULIA SUSANA','firstName'=>'CABALLERO','lastName'=>'CAORSI'),
            array('identityCard'=>'100000274','names'=>'DIAMELA','firstName'=>'FUSCO','lastName'=>'CHEVESTE'),
            array('identityCard'=>'100000275','names'=>'SILVANA','firstName'=>'SUBURU','lastName'=>'GARCIA'),
            array('identityCard'=>'100000276','names'=>'MANUEL JOAQUIN','firstName'=>'RAMOS','lastName'=>'GORENA'),
            array('identityCard'=>'100000277','names'=>'ANA MARIA','firstName'=>'XAVIER','lastName'=>'ALOUY'),
            array('identityCard'=>'100000278','names'=>'GRACIELA TERESITA','firstName'=>'ALVAREZ','lastName'=>'DODERA'),
            array('identityCard'=>'100000279','names'=>'ERNESTO GABRIEL','firstName'=>'BENITEZ','lastName'=>'CORTABARIA'),
            array('identityCard'=>'100000280','names'=>'FRANCISCO SNATIAGO','firstName'=>'CARAMBULA','lastName'=>'PAIS'),
            array('identityCard'=>'100000281','names'=>'FLAVIO GUSTAVO','firstName'=>'CHIESA','lastName'=>'GUIMARAES'),
            array('identityCard'=>'100000282','names'=>'GARY ASTUL','firstName'=>'CORUJO','lastName'=>'SCAGNEGATTI'),
            array('identityCard'=>'100000283','names'=>'MARIA LILIAN','firstName'=>'DA ROSA','lastName'=>'DUPIN'),
            array('identityCard'=>'100000284','names'=>'ENZO','firstName'=>'GRAÑA','lastName'=>'USERA'),
            array('identityCard'=>'100000285','names'=>'ESTELA','firstName'=>'MACIEL','lastName'=>'DUQUE'),
            array('identityCard'=>'100000286','names'=>'GLORIA DEL CARMEN','firstName'=>'SOUTULLO','lastName'=>'SANTILLANO'),
            array('identityCard'=>'100000287','names'=>'ANTONIO','firstName'=>'LAFUENTE','lastName'=>'CARRAU'),
            array('identityCard'=>'100000288','names'=>'JUAN JOSÉ','firstName'=>'SOSA','lastName'=>'ALVAREZ'),
            array('identityCard'=>'100000289','names'=>'ROBERTO CARLOS','firstName'=>'SARAVIA','lastName'=>'ABOAL'),
            array('identityCard'=>'100000290','names'=>'ANA MARIA','firstName'=>'ROMANO','lastName'=>'CASTRO'),
            array('identityCard'=>'100000291','names'=>'JESUS','firstName'=>'RODRIGUEZ','lastName'=>'SEGUESSA'),
            array('identityCard'=>'100000292','names'=>'ALVARO','firstName'=>'LATCHINIAN','lastName'=>'MORAES'),
            array('identityCard'=>'100000293','names'=>'WILSON JESUS','firstName'=>'LUCAS','lastName'=>'QUINTEROS'),
            array('identityCard'=>'100000294','names'=>'ANIBAL JOSE ENRIQUE','firstName'=>'ISLAS','lastName'=>'QUINTEROS'),
            array('identityCard'=>'100000295','names'=>'BERTIL RANDOLF','firstName'=>'CABRAL','lastName'=>'SOTO'),
            array('identityCard'=>'100000296','names'=>'MARTHA CATALINA','firstName'=>'ABARNO','lastName'=>'MACAGNO'),
            array('identityCard'=>'100000297','names'=>'MARIA DEL CARMEN','firstName'=>'CANCELA','lastName'=>'REBOREDO'),
            array('identityCard'=>'100000298','names'=>'WALTER ENRIQUE','firstName'=>'PISANO','lastName'=>'CORVO'),
            array('identityCard'=>'100000299','names'=>'MARIO ESTEBAN','firstName'=>'FERRE','lastName'=>'FLORES'),
            array('identityCard'=>'100000300','names'=>'CARLOS','firstName'=>'REYES','lastName'=>'ALVAREZ'),
            array('identityCard'=>'100000301','names'=>'HECTOR FRANCISCO','firstName'=>'PORTE','lastName'=>'MOYANO'),
            array('identityCard'=>'100000302','names'=>'JAVIER','firstName'=>'OLIVERA','lastName'=>'SOSA'),
            array('identityCard'=>'100000303','names'=>'LILIANA BEATRIZ','firstName'=>'CASTAINGDEBAT','lastName'=>'BONJOUR'),
            array('identityCard'=>'100000304','names'=>'JUAN PABLO','firstName'=>'MACHADO','lastName'=>'LEUNDA'),
            array('identityCard'=>'100000305','names'=>'GUSTAVO DANIEL','firstName'=>'BARRIOS','lastName'=>'SOLE'),
            array('identityCard'=>'100000306','names'=>'JIMMY WILSON','firstName'=>'IROLDI','lastName'=>'MENDARO'),
            array('identityCard'=>'100000307','names'=>'RICARDO CARLOS','firstName'=>'TERRA','lastName'=>'BARRETO'),
            array('identityCard'=>'100000308','names'=>'MARIA DEL CARMEN','firstName'=>'TOSCANO','lastName'=>'AROCENA'),
            array('identityCard'=>'100000309','names'=>'MA. DEL ROSARIO','firstName'=>'SILVA','lastName'=>'CERCHI'),
            array('identityCard'=>'100000310','names'=>'JUAN ANGEL','firstName'=>'SORONDO','lastName'=>'CAFFERATA'),
            array('identityCard'=>'100000311','names'=>'AZUCENA ESTEFANIA','firstName'=>'ALCINA','lastName'=>'BONILLA'),
            array('identityCard'=>'100000312','names'=>'ANA MARIA','firstName'=>'PERTUSATTI','lastName'=>'BARELLA'),
            array('identityCard'=>'100000313','names'=>'ELIZABETH MARIA','firstName'=>'MODERNELL','lastName'=>'CASERTA'),
            array('identityCard'=>'100000314','names'=>'ANDRES','firstName'=>'ESQUIVEL','lastName'=>'FERNANDEZ'),
            array('identityCard'=>'100000315','names'=>'IGNACIO','firstName'=>'DALL´ORSO','lastName'=>'ROBERTI'),
            array('identityCard'=>'100000316','names'=>'HEBER ISIDRO','firstName'=>'SANCHEZ','lastName'=>'SALOMON'),
            array('identityCard'=>'100000317','names'=>'ALEJANDRO MIGUEL','firstName'=>'VITALE','lastName'=>'JAUREGUI'),
            array('identityCard'=>'100000318','names'=>'SERGIO LEONEL','firstName'=>'LARRAÑAGA','lastName'=>'MENDOZA'),
            array('identityCard'=>'100000319','names'=>'MAURICIO','firstName'=>'SUAREZ','lastName'=>'LUTZ'),
            array('identityCard'=>'100000320','names'=>'EDUARDO','firstName'=>'PIGNATARO','lastName'=>'IBIÑETE'),


        );


        foreach ($personsarray as $key) {
                DB::table('persons')->insert([
                [
                    'identity_Card' => $key['identityCard'], 
                    'identity_Card_Type' => 'CI',
                    'identity_Card_Ext' => 'CB',
                    'names' => $key['names'],
                    'first_Name' => $key['firstName'],
                    'last_Name' => $key['lastName'],
                    'birth_Date' => date("Y-m-d H:i:s"),
                    'gender' => 'M',
                    'address' => null,
                    'telephone' => null,
                    'email' => null,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s")
                ],
            ]);
        }


    }
}
