<?php

use Illuminate\Database\Seeder;

class vehiclesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        
    	$vehicles = array(
    		array('plate_number'=>'4378VBN','brand'=>'SUZUKI','model'=>'S-CROSS'),
			array('plate_number'=>'4869FPX','brand'=>'TOYOTA','model'=>'AYGO'),
			array('plate_number'=>'2946RST','brand'=>'MITSUBISHI','model'=>'ASX'),
			array('plate_number'=>'8258RCB','brand'=>'TOYOTA','model'=>'COROLLA'),
			array('plate_number'=>'5966LMA','brand'=>'SUZUKI','model'=>'IGNIS'),
			array('plate_number'=>'7298DQS','brand'=>'TOYOTA','model'=>'C-HR'),
			array('plate_number'=>'2542SXT','brand'=>'VOLKSWAGEN','model'=>'ARTEON'),
			array('plate_number'=>'5564MCZ','brand'=>'KIA','model'=>'RIO'),
			array('plate_number'=>'4442KAV','brand'=>'VOLKSWAGEN','model'=>'GOLF'),
			array('plate_number'=>'5965APG','brand'=>'SUZUKI','model'=>'ACROSS'),
			array('plate_number'=>'5989XDH','brand'=>'TOYOTA','model'=>'CAMRY'),
			array('plate_number'=>'5934LEL','brand'=>'KIA','model'=>'PICANTO'),
			array('plate_number'=>'2789YQK','brand'=>'SUZUKI','model'=>'S-CROSS'),
			array('plate_number'=>'8264RWA','brand'=>'TOYOTA','model'=>'AYGO'),
			array('plate_number'=>'9434KJN','brand'=>'MITSUBISHI','model'=>'ASX'),
			array('plate_number'=>'8365QMV','brand'=>'TOYOTA','model'=>'COROLLA'),
			array('plate_number'=>'6927FFD','brand'=>'SUZUKI','model'=>'IGNIS'),
			array('plate_number'=>'4836UPN','brand'=>'TOYOTA','model'=>'C-HR'),
			array('plate_number'=>'8778XEA','brand'=>'VOLKSWAGEN','model'=>'ARTEON'),
			array('plate_number'=>'8582SEP','brand'=>'KIA','model'=>'RIO'),
			array('plate_number'=>'6358VRN','brand'=>'VOLKSWAGEN','model'=>'GOLF'),
			array('plate_number'=>'8359BLN','brand'=>'SUZUKI','model'=>'ACROSS'),
			array('plate_number'=>'3493TGW','brand'=>'TOYOTA','model'=>'CAMRY'),
			array('plate_number'=>'3254QJR','brand'=>'KIA','model'=>'PICANTO'),
			array('plate_number'=>'6997YTX','brand'=>'SUZUKI','model'=>'S-CROSS'),
			array('plate_number'=>'2857MLQ','brand'=>'TOYOTA','model'=>'AYGO'),
			array('plate_number'=>'3684RZZ','brand'=>'MITSUBISHI','model'=>'ASX'),
			array('plate_number'=>'8465KMR','brand'=>'TOYOTA','model'=>'COROLLA'),
			array('plate_number'=>'2779FKF','brand'=>'SUZUKI','model'=>'IGNIS'),
			array('plate_number'=>'9954ZTE','brand'=>'TOYOTA','model'=>'C-HR'),
			array('plate_number'=>'2989XDY','brand'=>'VOLKSWAGEN','model'=>'ARTEON'),
			array('plate_number'=>'8727DHP','brand'=>'KIA','model'=>'RIO'),
			array('plate_number'=>'2372QEE','brand'=>'VOLKSWAGEN','model'=>'GOLF'),
			array('plate_number'=>'8694EDP','brand'=>'SUZUKI','model'=>'ACROSS'),
			array('plate_number'=>'3825PTA','brand'=>'TOYOTA','model'=>'CAMRY'),
			array('plate_number'=>'4379USZ','brand'=>'KIA','model'=>'PICANTO'),
			array('plate_number'=>'3873ZDC','brand'=>'SUZUKI','model'=>'S-CROSS'),
			array('plate_number'=>'4785USY','brand'=>'TOYOTA','model'=>'AYGO'),
			array('plate_number'=>'8892ZSV','brand'=>'MITSUBISHI','model'=>'ASX'),
			array('plate_number'=>'7638DBV','brand'=>'TOYOTA','model'=>'COROLLA'),
			array('plate_number'=>'4699FVW','brand'=>'SUZUKI','model'=>'IGNIS'),
			array('plate_number'=>'4566XUU','brand'=>'TOYOTA','model'=>'C-HR'),
			array('plate_number'=>'2275FKU','brand'=>'VOLKSWAGEN','model'=>'ARTEON'),
			array('plate_number'=>'9625VYW','brand'=>'KIA','model'=>'RIO'),
			array('plate_number'=>'7229PTK','brand'=>'VOLKSWAGEN','model'=>'GOLF'),
			array('plate_number'=>'3447EXQ','brand'=>'SUZUKI','model'=>'ACROSS'),
			array('plate_number'=>'6649HHR','brand'=>'TOYOTA','model'=>'CAMRY'),
			array('plate_number'=>'2996EES','brand'=>'KIA','model'=>'PICANTO'),
			array('plate_number'=>'6493FKQ','brand'=>'SUZUKI','model'=>'S-CROSS'),
			array('plate_number'=>'6675VJD','brand'=>'TOYOTA','model'=>'AYGO'),
			array('plate_number'=>'3997PRC','brand'=>'MITSUBISHI','model'=>'ASX'),
			array('plate_number'=>'7747EVW','brand'=>'TOYOTA','model'=>'COROLLA'),
			array('plate_number'=>'4956UST','brand'=>'SUZUKI','model'=>'IGNIS'),
			array('plate_number'=>'6543NFD','brand'=>'TOYOTA','model'=>'C-HR'),
			array('plate_number'=>'9399HHG','brand'=>'VOLKSWAGEN','model'=>'ARTEON'),
			array('plate_number'=>'3825GCF','brand'=>'KIA','model'=>'RIO'),
			array('plate_number'=>'4488LXZ','brand'=>'VOLKSWAGEN','model'=>'GOLF'),
			array('plate_number'=>'5237QYC','brand'=>'SUZUKI','model'=>'ACROSS'),
			array('plate_number'=>'9496AEZ','brand'=>'TOYOTA','model'=>'CAMRY'),
			array('plate_number'=>'3758TBK','brand'=>'KIA','model'=>'PICANTO'),
			array('plate_number'=>'7599KTS','brand'=>'SUZUKI','model'=>'S-CROSS'),
			array('plate_number'=>'6399RSF','brand'=>'TOYOTA','model'=>'AYGO'),
			array('plate_number'=>'8565YZZ','brand'=>'MITSUBISHI','model'=>'ASX'),
			array('plate_number'=>'6973XXN','brand'=>'TOYOTA','model'=>'COROLLA'),
			array('plate_number'=>'3867PCR','brand'=>'SUZUKI','model'=>'IGNIS'),
			array('plate_number'=>'6658QGN','brand'=>'TOYOTA','model'=>'C-HR'),
			array('plate_number'=>'4989CYG','brand'=>'VOLKSWAGEN','model'=>'ARTEON'),
			array('plate_number'=>'3745YFR','brand'=>'KIA','model'=>'RIO'),
			array('plate_number'=>'9235YTV','brand'=>'VOLKSWAGEN','model'=>'GOLF'),
			array('plate_number'=>'3326MPE','brand'=>'SUZUKI','model'=>'ACROSS'),
			array('plate_number'=>'5843HRQ','brand'=>'TOYOTA','model'=>'CAMRY'),
			array('plate_number'=>'3875GZG','brand'=>'KIA','model'=>'PICANTO'),
			array('plate_number'=>'9422BEP','brand'=>'SUZUKI','model'=>'S-CROSS'),
			array('plate_number'=>'9672LUW','brand'=>'TOYOTA','model'=>'AYGO'),
			array('plate_number'=>'2932XLU','brand'=>'MITSUBISHI','model'=>'ASX'),
			array('plate_number'=>'9639UXP','brand'=>'TOYOTA','model'=>'COROLLA'),
			array('plate_number'=>'2773PSG','brand'=>'SUZUKI','model'=>'IGNIS'),
			array('plate_number'=>'4282WTF','brand'=>'TOYOTA','model'=>'C-HR'),
			array('plate_number'=>'7327VTZ','brand'=>'VOLKSWAGEN','model'=>'ARTEON'),
			array('plate_number'=>'3454PAU','brand'=>'KIA','model'=>'RIO'),
			array('plate_number'=>'9324CNF','brand'=>'VOLKSWAGEN','model'=>'GOLF'),
			array('plate_number'=>'8468GRD','brand'=>'SUZUKI','model'=>'ACROSS'),
			array('plate_number'=>'9347SYD','brand'=>'TOYOTA','model'=>'CAMRY'),
			array('plate_number'=>'8275SHM','brand'=>'KIA','model'=>'PICANTO'),
			array('plate_number'=>'7548WQN','brand'=>'SUZUKI','model'=>'S-CROSS'),
			array('plate_number'=>'3297REK','brand'=>'TOYOTA','model'=>'AYGO'),
			array('plate_number'=>'5625SZS','brand'=>'MITSUBISHI','model'=>'ASX'),
			array('plate_number'=>'4483JEQ','brand'=>'TOYOTA','model'=>'COROLLA'),
			array('plate_number'=>'5825FKJ','brand'=>'SUZUKI','model'=>'IGNIS'),
			array('plate_number'=>'2439SXL','brand'=>'TOYOTA','model'=>'C-HR'),
			array('plate_number'=>'8333ZQM','brand'=>'VOLKSWAGEN','model'=>'ARTEON'),
			array('plate_number'=>'5329QMT','brand'=>'KIA','model'=>'RIO'),
			array('plate_number'=>'3475VWJ','brand'=>'VOLKSWAGEN','model'=>'GOLF'),
			array('plate_number'=>'4827AEA','brand'=>'SUZUKI','model'=>'ACROSS'),
			array('plate_number'=>'7228CKG','brand'=>'TOYOTA','model'=>'CAMRY'),
			array('plate_number'=>'8843LYA','brand'=>'KIA','model'=>'PICANTO'),
			array('plate_number'=>'8983TYR','brand'=>'SUZUKI','model'=>'S-CROSS'),
			array('plate_number'=>'3976AJW','brand'=>'TOYOTA','model'=>'AYGO'),
			array('plate_number'=>'5257ANQ','brand'=>'MITSUBISHI','model'=>'ASX'),
			array('plate_number'=>'8224AKU','brand'=>'TOYOTA','model'=>'COROLLA'),
			array('plate_number'=>'8953HZZ','brand'=>'SUZUKI','model'=>'IGNIS'),
			array('plate_number'=>'4584WNZ','brand'=>'TOYOTA','model'=>'C-HR'),
			array('plate_number'=>'2739MPR','brand'=>'VOLKSWAGEN','model'=>'ARTEON'),
			array('plate_number'=>'8658CWU','brand'=>'KIA','model'=>'RIO'),
			array('plate_number'=>'3663QSM','brand'=>'VOLKSWAGEN','model'=>'GOLF'),
			array('plate_number'=>'6288CPB','brand'=>'SUZUKI','model'=>'ACROSS'),
			array('plate_number'=>'7827CTT','brand'=>'TOYOTA','model'=>'CAMRY'),
			array('plate_number'=>'2556TGV','brand'=>'KIA','model'=>'PICANTO'),
			array('plate_number'=>'4867XRL','brand'=>'SUZUKI','model'=>'S-CROSS'),
			array('plate_number'=>'2774BGH','brand'=>'TOYOTA','model'=>'AYGO'),
			array('plate_number'=>'6322EDN','brand'=>'MITSUBISHI','model'=>'ASX'),
			array('plate_number'=>'3628BYF','brand'=>'TOYOTA','model'=>'COROLLA'),
			array('plate_number'=>'2272AJQ','brand'=>'SUZUKI','model'=>'IGNIS'),
			array('plate_number'=>'7547GRJ','brand'=>'TOYOTA','model'=>'C-HR'),
			array('plate_number'=>'5266EKD','brand'=>'VOLKSWAGEN','model'=>'ARTEON'),
			array('plate_number'=>'5995YZH','brand'=>'KIA','model'=>'RIO'),
			array('plate_number'=>'2583PUY','brand'=>'VOLKSWAGEN','model'=>'GOLF'),
			array('plate_number'=>'8587HEY','brand'=>'SUZUKI','model'=>'ACROSS'),
			array('plate_number'=>'8235VFM','brand'=>'TOYOTA','model'=>'CAMRY'),
			array('plate_number'=>'8692DHV','brand'=>'KIA','model'=>'PICANTO'),
			array('plate_number'=>'8385BTA','brand'=>'SUZUKI','model'=>'S-CROSS'),
			array('plate_number'=>'2779VPK','brand'=>'TOYOTA','model'=>'AYGO'),
			array('plate_number'=>'4545RSK','brand'=>'MITSUBISHI','model'=>'ASX'),
			array('plate_number'=>'2586TQV','brand'=>'TOYOTA','model'=>'COROLLA'),
			array('plate_number'=>'6865XQU','brand'=>'SUZUKI','model'=>'IGNIS'),
			array('plate_number'=>'8966RYZ','brand'=>'TOYOTA','model'=>'C-HR'),
			array('plate_number'=>'2572GCY','brand'=>'VOLKSWAGEN','model'=>'ARTEON'),
			array('plate_number'=>'2663GHA','brand'=>'KIA','model'=>'RIO'),
			array('plate_number'=>'9687CLF','brand'=>'VOLKSWAGEN','model'=>'GOLF'),
			array('plate_number'=>'5833VVB','brand'=>'SUZUKI','model'=>'ACROSS'),
			array('plate_number'=>'4945EGT','brand'=>'TOYOTA','model'=>'CAMRY'),
			array('plate_number'=>'8278UYV','brand'=>'KIA','model'=>'PICANTO'),
			array('plate_number'=>'4736YWF','brand'=>'SUZUKI','model'=>'S-CROSS'),
			array('plate_number'=>'6682LYX','brand'=>'TOYOTA','model'=>'AYGO'),
			array('plate_number'=>'4798FMB','brand'=>'MITSUBISHI','model'=>'ASX'),
			array('plate_number'=>'9957JDJ','brand'=>'TOYOTA','model'=>'COROLLA'),
			array('plate_number'=>'7962EQG','brand'=>'SUZUKI','model'=>'IGNIS'),
			array('plate_number'=>'4397UKK','brand'=>'TOYOTA','model'=>'C-HR'),
			array('plate_number'=>'6995YFL','brand'=>'VOLKSWAGEN','model'=>'ARTEON'),
			array('plate_number'=>'3745CFL','brand'=>'KIA','model'=>'RIO'),
			array('plate_number'=>'2589CTF','brand'=>'VOLKSWAGEN','model'=>'GOLF'),
			array('plate_number'=>'7767ZPZ','brand'=>'SUZUKI','model'=>'ACROSS'),
			array('plate_number'=>'8383KFX','brand'=>'TOYOTA','model'=>'CAMRY'),
			array('plate_number'=>'7782RNH','brand'=>'KIA','model'=>'PICANTO'),
			array('plate_number'=>'2897CLZ','brand'=>'SUZUKI','model'=>'S-CROSS'),
			array('plate_number'=>'6726XFZ','brand'=>'TOYOTA','model'=>'AYGO'),
			array('plate_number'=>'2433WZL','brand'=>'MITSUBISHI','model'=>'ASX'),
			array('plate_number'=>'6956ALA','brand'=>'TOYOTA','model'=>'COROLLA'),
			array('plate_number'=>'7887FTX','brand'=>'SUZUKI','model'=>'IGNIS'),
			array('plate_number'=>'3683YSM','brand'=>'TOYOTA','model'=>'C-HR'),
			array('plate_number'=>'2833DTG','brand'=>'VOLKSWAGEN','model'=>'ARTEON'),
			array('plate_number'=>'6245ATA','brand'=>'KIA','model'=>'RIO'),
			array('plate_number'=>'6595SPS','brand'=>'VOLKSWAGEN','model'=>'GOLF'),
			array('plate_number'=>'8695MJA','brand'=>'SUZUKI','model'=>'ACROSS'),
			array('plate_number'=>'6837LHT','brand'=>'TOYOTA','model'=>'CAMRY'),
			array('plate_number'=>'8382YWR','brand'=>'KIA','model'=>'PICANTO'),
			array('plate_number'=>'9439QMH','brand'=>'SUZUKI','model'=>'S-CROSS'),
			array('plate_number'=>'4726HRX','brand'=>'TOYOTA','model'=>'AYGO'),
			array('plate_number'=>'7784PYJ','brand'=>'MITSUBISHI','model'=>'ASX'),
			array('plate_number'=>'4394NJE','brand'=>'TOYOTA','model'=>'COROLLA'),

    	);


        foreach ($vehicles as $key) {
			DB::table('vehicles')->insert([
	            [
	                'plate_number' => $key['plate_number'],
	                'brand' => $key['brand'],
	                'model' => $key['model'],
	                'created_at' => date("Y-m-d H:i:s"),
	                'updated_at' => date("Y-m-d H:i:s")
	            ],
			]);

		}
    }
}
